name: flutter_bluetooth_serial_example
version: 0.4.0
description: Demonstrates how to use the `flutter_bluetooth_serial` plugin.
authors:
  - Patryk Ludwikowski <patryk.ludwikowski.7@gmail.com>
homepage: https://github.com/edufolly/flutter_bluetooth_serial/tree/master/example/

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  scoped_model: ^2.0.0-nullsafety.0
  cupertino_icons: ^1.0.3
  animated_splash_screen: ^1.3.0
  flutter_bluetooth_serial: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: DancingScript-VariableFont_wght
      fonts:
        - asset: assets/fonts/DancingScript-VariableFont_wght.ttf
        
    - family: DancingScript-Bold
      fonts:
        - asset: assets/fonts/DancingScript-Bold.ttf

    - family: BurbankBigCondensed-Black
      fonts:
        - asset: assets/fonts/BurbankBigCondensed-Black.ttf

    - family: RobotoSlab-VariableFont_wght
      fonts:
        - asset: assets/fonts/RobotoSlab-VariableFont_wght.ttf 